### ISSUE TITLE
eps and k values

### ISSUE THREAD

**Issue by theodeprelle** [Colin97/MSN-Point-Cloud-Completion#18]
Hi Colin,

I have an other question regarding the eps and k parameters for the EMD loss. Could you provide a more detail explanation of their purpose ?

Thanks,

**Comment by Colin97** [comment]
The EMD implementation is based on an approximation algorithm (auction algorithm). It employs a parameter eps to balance the error rate and the speed of convergence. Smaller eps achieves more optimal assignment but needs a longer time for convergence. The time complexity is $O(n^2k)$, where $k$ is the number of iterations. Since it may take a long time to achieve the convergence (one-one matching), we set a fixed number of iterations,  and our implementation thus cannot guarantee a (but near) one-one matching, which means there may be a small number of “many to one” pairs in our results. 

For a given eps,  as k increases, there will be fewer "one-to-many" pairs and the result will be more accurate.

We set a $eps = 0.005, k = 50$ during training and a $eps = 0.002, k = 10000$ during testing.

Please refer to the [paper](https://dspace.mit.edu/bitstream/handle/1721.1/3265/P-2108-26912652.pdf?sequence=1&isAllowed=y) for the role of eps.

**Comment by theodeprelle** [comment]
Thanks! In your code you are using a block size of 2048. If I halve it size, do I have to change the values of k and eps ?

**Comment by Colin97** [comment]
I do not think so.

> Thanks! In your code you are using a block size of 2048. If I halve it size, do I have to change the values of k and eps ?
