### ISSUE TITLE
How to change the EMD wrapper to deal with flexible number of points instead of 1024x?

### ISSUE THREAD

**Issue by AmmonZ** [Colin97/MSN-Point-Cloud-Completion#9]
Hi, Thank you for your good job! How to change the EMD wrapper to deal with flexible number of points,  instead of just 1024x?

**Comment by Colin97** [comment]
In order to support other numbers of points, you may need to change:

emd_cuda.cu: replace 1024 with another number K. K should be no greater than 1024 and be a factor of n.
emd_module.py: remove the assert statement.

I am not sure whether it is enough. Please let me know if you encounter any other problems.
